#!/usr/bin/env sh

set -e

PKGNAME="blacklists"
PKGVER="2.1"
PKGREL="0"
PKGARCH="arm64"
PKGMAINT="Dave King <dave@daveking.com>"
PKGDESC="Configure iptables on the UDM Pro to block traffic from the IP addresses listed in the active ntopng blacklists.  The list of blocked addresses is updated once a day from the source."

BUILDDIR=${PKGNAME}_${PKGVER}-${PKGREL}_${PKGARCH}

rm -fr ${BUILDDIR} &>/dev/null
mkdir -p ${BUILDDIR}/DEBIAN
mkdir -p ${BUILDDIR}/etc/systemd/system
mkdir -p ${BUILDDIR}/usr/bin
mkdir -p ${BUILDDIR}/data/blacklists

cp -v postinst ${BUILDDIR}/DEBIAN/
cp -v blacklists.timer blacklists.service ${BUILDDIR}/etc/systemd/system/
cp -v blacklists ${BUILDDIR}/usr/bin/
cp -v blacklists.conf.sample ${BUILDDIR}/data/blacklists/
chmod 755 ${BUILDDIR}/usr/bin/blacklists

cat <<_EOF_ >${BUILDDIR}/DEBIAN/control
Package: ${PKGNAME}
Version: ${PKGVER}
Architecture: ${PKGARCH}
Maintainer: ${PKGMAINT}
Description: ${PKGDESC}
Depends: udmpro-al324-base-files (>=3), ntopng, ntopng-data
_EOF_

dpkg-deb --build --root-owner-group ${BUILDDIR}

mv -v ${BUILDDIR}.deb ${HOME}/src/udm-hacks/ppa/pool/main/b/blacklists/

${HOME}/src/udm-hacks/update_ppa

rm -fr ${BUILDDIR}
