#!/usr/bin/env sh

set -e

PKGNAME="openvpn-server"
PKGVER="1.0"
PKGREL="0"
PKGARCH="arm64"
PKGMAINT="Dave King <dave@daveking.com>"
PKGDESC="Running an OpenVPN Server on the Ubiquiti Dream Machine Pro
 This package contains the configuration files and scripts necessary to run OpenVPN on the UDM as a server for remote clients"

BUILDDIR=${PKGNAME}_${PKGVER}-${PKGREL}_${PKGARCH}

rm -fr ${BUILDDIR} &>/dev/null
mkdir -p $BUILDDIR
mkdir -p ${BUILDDIR}/data/easyrsa
mkdir -p ${BUILDDIR}/data/openvpn
mkdir ${BUILDDIR}/DEBIAN
mkdir -p ${BUILDDIR}/etc/default
mkdir -p ${BUILDDIR}/etc/systemd/system
mkdir -p ${BUILDDIR}/usr/bin

cp -v openvpn-server.conf ${BUILDDIR}/data/openvpn/
cp -v postinst ${BUILDDIR}/DEBIAN/
cp -v openvpn-server.defaults ${BUILDDIR}/etc/default/openvpn-server
cp -v openvpn-server.service ${BUILDDIR}/etc/systemd/system/
cp -v mk-ovpn openvpn-server-iptables-rules ${BUILDDIR}/usr/bin/

#  Use a specific version of EasyRSA because its commands and command line options keep changing
EASYRSA="3.1.2"
wget -P /tmp/ https://github.com/OpenVPN/easy-rsa/releases/download/v${EASYRSA}/EasyRSA-${EASYRSA}.tgz
tar -C ${BUILDDIR}/data/easyrsa --strip-components=1 -xf /tmp/EasyRSA-${EASYRSA}.tgz
rm /tmp/EasyRSA-${EASYRSA}.tgz

cat <<_EOF_ >${BUILDDIR}/DEBIAN/control
Package: ${PKGNAME}
Version: ${PKGVER}
Architecture: ${PKGARCH}
Maintainer: ${PKGMAINT}
Description: ${PKGDESC}
_EOF_

dpkg-deb --build --root-owner-group ${BUILDDIR}
#  dpkg-sig doesn't exist on Fedora ????
#GNUPGHOME=${HOME}/src/udm-hacks/.gnupg
#dpkg-sig --sign builder -k udm-hacks-repo@daveking.com *.deb

mv -v ${BUILDDIR}.deb ${HOME}/src/udm-hacks/ppa/pool/main/o/openvpn-server/

${HOME}/src/udm-hacks/update_ppa

rm -fr ${BUILDDIR}
