#!/bin/sh -e

# Previous package version on upgrade
PREV_VERSION=$2

case "$1" in
    configure)
	# continue below
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
	exit 0
    ;;

    *)
	echo "postinst called with unknown argument \`$1'" >&2
	exit 0
    ;;
esac

umask 022

#  Use /volume1 as the persistent store if it exists, otherwise use /data
DATADIR="/data/openvpn"
if [ -d /volume1/.srv ]; then
	DATADIR="/volume1/openvpn"
	if [ ! -d $DATADIR ]; then
		mkdir $DATADIR
		mv /data/openvpn/* ${DATADIR}/ &>/dev/null
	fi
	sed -i "s|DATADIR=\"/data/openvpn\"/DATADIR=\"${DATADIR}\"|" "/etc/default/openvpn-server"
	sed -i "s|/data/openvpn|${DATADIR}|g" "${DATADIR}/server/openvpn-server.conf"
fi

echo "\nopenvpn-server keeps its persistent data in the $DTATDIR directory."

echo -e "\nManual steps are required to complete the OpenVPN server configuration:"
echo -e "\n1) Run \"create-openvpn-server-ca\" to configure the EasyRSA certificate"
echo "   authority used to create client certificates and OPVN configuration files."
echo "2) Set the  HOSTNAME and VPNPORT values in \"/etc/default/openvpn-server\" to"
echo "   those that are used to access this server from the internet."
echo "3) Issue these commands to start the openvpn server now and automatically in"
echo "   the future:"
echo "     systemctl start openvpn"
echo "     systemctl enable openvpn-server"
echo "4) Generate client sertificates and OpenVPN configuration files using the"
echo -e "   \"mk-ovpn\" command.\n"

exit 0
